version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-database}
      DATABASE_PORT: ${DATABASE_PORT:-1433}
      DATABASE_NAME: ${DATABASE_NAME:-dev}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-superADMIN123!@#}
    ports:
      - "${API_EXTERNAL_PORT:-3000}:80"
    container_name: cadastro-pesquisa-backend
    restart: always

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: cadastro-pesquisa-database
    restart: always
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD:-superADMIN123!@#}
      DATABASE_NAME: ${DATABASE_NAME:-dev}
      ACCEPT_EULA: Y
    ports:
      - "${DATABASE_EXTERNAL_PORT:-1433}:1433"
    volumes:
      - ./database:/var/opt/mssql/data
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./setup-ddls.sh:/docker-entrypoint-initdb.d/setup-ddls.sh
    entrypoint: /docker-entrypoint-initdb.d/entrypoint.sh