version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "3000:80"
    container_name: cadastro-pesquisa-backend
    restart: always

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: cadastro-pesquisa-database
    restart: always
    environment:
      SA_PASSWORD: superADMIN123!@#
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./database:/var/opt/mssql/data
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./setup-ddls.sh:/docker-entrypoint-initdb.d/setup-ddls.sh
    entrypoint: /docker-entrypoint-initdb.d/entrypoint.sh